# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LxH5Jy1W-3gay96YVXrDG_BvXePBOKuH
"""

# Commented out IPython magic to ensure Python compatibility.
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np
import pandas as pd

(x_train,y_train) ,(x_test,y_test) = keras.datasets.mnist.load_data()

len(x_train)

x_train=x_train/255
x_test = x_test/255
print(x_train[0])

x_train[0].shape

plt.matshow(x_train[0])

y_train[0]

x_train_flat = x_train.reshape(len(x_train),28*28)
x_test_flat= x_test.reshape(len(x_test),28*28)

x_train_flat.shape

model = keras.Sequential([
              keras.layers.Dense(10,input_shape=(784,),activation='sigmoid')
])
model.compile(
    optimizer= 'adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)
model.fit(x_train_flat,y_train,epochs=5)

model.evaluate(x_test_flat,y_test)

y_predict = model.predict(x_test_flat)
y_predict[0]

np.argmax(y_predict[0])

plt.matshow(x_test[0])

